services:
  nginx:
    image: nginx:alpine
    container_name: nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on: 
      - api

  api:
    build: .
    container_name: fastapi_api

    env_file:
      - .env.local

    expose:
      - "8000"

    volumes:
      - .:/app

    command: >
      sh -c "
      alembic upgrade head &&
      gunicorn main:app -k uvicorn.workers.UvicornWorker -w ${WORKER_PROCESSES} -b 0.0.0.0:8000
      "